// Capturas de la interfaz para revisión visual.
import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
const PORT = 4177;
const server = spawn('npx', ['vite', 'preview', '--port', String(PORT), '--strictPort'], { stdio: 'pipe', detached: true });
await new Promise((r) => server.stdout.on('data', (d) => String(d).includes('localhost') && r()));
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
process.on('exit', () => { try { process.kill(-server.pid); } catch {} });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 }, serviceWorkers: 'block' })).newPage();
const call = (m, ...a) => page.evaluate(([m, a]) => window.__lienzo.call(m, ...a), [m, a]);
const wait = (ms = 300) => page.waitForTimeout(ms);
const out = process.argv[2] ?? 'tests/shots';
await page.goto(`http://localhost:${PORT}/`);
await page.waitForFunction(() => window.__lienzoStore?.getState().ready);
await page.screenshot({ path: `${out}-0-inicio.png` });
await call('newDoc', 1200, 800, 'white', 'Cartel.psd');
await call('applyGradient', [0, 0], [1200, 800], 'linear');
await call('newLayer'); await call('selectShape', { x: 150, y: 150, w: 400, h: 400 }, 'ellipse', 'replace', 0); await call('fill', [230, 60, 60, 255]); await call('deselect');
await call('setEffects', (await page.evaluate(() => window.__lienzoStore.getState().doc.activeLayerId)), { dropShadow: { enabled: true, color: [0, 0, 0, 255], opacity: 0.6, angle: 120, distance: 20, size: 15 } }, true);
await call('createText', { text: 'Lienzo', x: 620, y: 300, size: 140, font: 'Arial', bold: true });
await call('newAdjustmentLayer', 'hueSat'); await call('addMask', 'reveal');
await call('selectShape', { x: 600, y: 500, w: 450, h: 200 }, 'rect', 'replace', 0);
await wait(600);
await page.screenshot({ path: `${out}-1-documento.png` });
await page.locator('.menubar .menu-root').nth(1).click(); await wait();
await page.screenshot({ path: `${out}-2-menu.png` });
await page.keyboard.press('Escape'); await page.mouse.click(700, 450); await wait();
await page.evaluate(() => window.__lienzoStore.getState().setDialog({ kind: 'adjust', type: 'curves' })); await wait(500);
await page.screenshot({ path: `${out}-3-curvas.png` });
await page.keyboard.press('Escape'); await wait();
await call('selectLayer', (await page.evaluate(() => window.__lienzoStore.getState().doc.layers[1].id)), false);
await page.evaluate(() => window.__lienzoStore.getState().setDialog({ kind: 'layerStyle' })); await wait(500);
await page.screenshot({ path: `${out}-4-estilo.png` });
await page.keyboard.press('Escape'); await wait();
await page.keyboard.press('Control+Alt+Shift+k'); await wait(500);
await page.screenshot({ path: `${out}-5-atajos.png` });
await page.keyboard.press('Escape'); await wait();
await call('deselect'); await page.keyboard.press('v'); await page.keyboard.press('Control+t'); await wait(500);
await page.screenshot({ path: `${out}-6-transformar.png` });
await browser.close(); process.kill(-server.pid);
